#### Оформление заказа
#POST http://localhost:5001/api/orders
#Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6IkZMT1JJU1QiLCJpYXQiOjE3NzM4Njc3ODAsImV4cCI6MTc3MzkxMDk4MH0.jcgvGZx7V5IV-8Y21odEf1__xW2hxRrhC7ulF4jGSlc
#
#{
#  "phone": "+996778145145",
#  "source": "WALK_IN",
#  "items": [
#    { "itemId": 2, "quantity": 15 }
#  ]
#}

### Оформление анонимного заказа (Без клиента)
POST http://localhost:5001/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6IkZMT1JJU1QiLCJpYXQiOjE3NzM4Njc3ODAsImV4cCI6MTc3MzkxMDk4MH0.jcgvGZx7V5IV-8Y21odEf1__xW2hxRrhC7ulF4jGSlc

{
  "source": "INSTAGRAM",
  "items": [
    { "itemId": 2, "quantity": 5 }
  ]
}